config/routes.rb
Rails.application.routes.draw do

  resources :songs

  get 'add_to_playlist/:song_id' => 'playlist#add', :as => 'add_to_playlist'
  post 'playlist/next' => 'playlist#get_next', :as => 'playlist_get_next'
  post 'playlist/show' => 'playlist#show', :as => 'show_playlist'
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :tag_values
  has_many :tags, :through => :tag_values
  # default_scope do
  #   where(:status => 0)
  # end
  after_save :store_in_cache
  def tag(label)
    self.tag_values.where(:tag_id => Tag.get_by_label(label.to_s).id).first
  end
  def self.from_file(path)
    s = Song.find_or_create_by(:filepath => path)
    s.filepath = path
    begin
      ID3Tag.read(File.open(path)) do |tag|
        s.set_tag(:artist, tag.get_frame(:TPE1).content)
        s.set_tag(:title, tag.get_frame(:TIT2).content)
        s.set_tag(:album, tag.get_frame(:TALB).content)
        s.set_tag(:year, tag.get_frame(:TYER).content)
      end
    rescue
      raise
      s.status = 1
    end
    s.save!
  end

  def add_tag(label, tag_value)
    tag = Tag.get_by_label(label)
    tag_value = TagValue.get_by_value(tag, tag_value)
    self.tag_values << tag_value
  end

  def set_tag(label, tag_value)
    tag = Tag.get_by_label(label)
    if self.tag_values.where(tag: tag).exists?
      self.tag_values.where(tag: tag).destroy
    end
    tag_value = TagValue.get_by_value(tag, tag_value)
    self.tag_values << tag_value
  end
  def store_in_cache
    sc = SongsCache.find_or_create_by(song: self)
    sc.title = self.tag(:title).to_s
    sc.artist = self.tag(:artist).to_s
    sc.album = self.tag(:album).to_s
    sc.save
  end
  def self.import_collection
    files = Array.new
    startpath = Rails.application.config.music_path
    directories = Array.new
    directories << startpath
    directories.each do |path|
      begin
        path = path[-1] == '/' ? "#{path}*" : "#{path}/*"
        Dir.glob(path).each do |file|
          if File.directory?(file)
            directories << file unless directories.include?(file)
          else
            # Song.from_file(file)
            files << file
          end
        end
      rescue
        puts "reading #{path} failed"
        raise
      end
    end
    Song.all.each do |s|
      files << s.filepath
    end
    files.each do |file|
      Song.from_file file
    end
  end
end

app/models/songs_cache.rb
class SongsCache < ActiveRecord::Base
  belongs_to :song

  def tag(t)
    puts t
    self.send(t)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :values, :class_name => 'TagValue'

  def self.get_by_label(value)
    Tag.where(:label => value).first_or_create
  end
end

app/models/tag_value.rb
class TagValue < ActiveRecord::Base
  belongs_to :tag
  has_and_belongs_to_many :songs

  def self.get_by_value(tag, value)
    tag.values.where(:value => value).first_or_create
  end

  def to_s
    self.value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController
  before_action do
    @playlist = session[:playlist]
  end
  def show
    @playlist = session[:playlist]
    respond_to do |format|
      format.js 
    end
  end
  def add
    song = Song.find(params[:song_id])
    session[:playlist] = Array.new unless session[:playlist]
    if song
      session[:playlist] << song
    end
    render 'show'
  end
  def get_next
    @song = @playlist.shift
    redirect_to @song
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = SongsCache.all
  end

  def show
    @song = Song.find(params[:id])
    respond_to do |format|
      format.mp3 do
        send_file @song.filepath, :type => 'audio/mpeg'
      end
      format.js 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicserver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 50px;">
<div class="navbar navbar-fixed-top">
  <div id="player">
    <audio controls="controls">
      <source src="" type='audio/mpeg' >
      Audio not supported.
    </audio>
    <%= link_to playlist_get_next_url(), :remote => true do %>
        <span class="glyphicon glyphicon-forward'"></span>
    <% end %>
  </div>
</div>

<div class="col-xs-9">
    <%= yield %>
</div>
<div class="col-xs-3">
  <div id="playlist">
    <%= render partial: 'playlist/show' %>
  </div>
</div>

</body>
</html>

app/views/playlist/_show.html.erb
<%=button_to 'odśwież', show_playlist_url, :remote => true %>
<%if @playlist %>
    <ul>
      <% @playlist.each do |song| %>
        <li>
          <%=song.tag(:title) %> by <%=song.tag(:artist) %>
        </li>
      <% end %>
    </ul>
<% end %>

app/views/playlist/show.js.erb
$('#playlist').html('<%= escape_javascript(render 'playlist/show') %>');

app/views/songs/_show.html.erb
<audio controls="controls">
  <source src="<%= song_url(@song, :format => :mp3) %>" type='audio/mpeg' >
  Audio not supported.
</audio>

app/views/songs/index.html.erb
<% if @songs %>
    <table class="table table-hover">
      <tr>
        <th>
          id
        </th>
        <th>
          tytuł
        </th>
        <th>
          wykonawca
        </th>
        <th>
          album
        </th>
        <td></td>
      </tr>
      <% @songs.each do |s| %>
        <tr>
          <td>
            <%= s.song_id %>
          </td>
          <td>
            <%= s.tag(:title) %>
          </td>
          <td>
            <%= s.tag(:artist) %>
          </td>
          <td>
            <%= s.tag(:album) %>
          </td>
          <td>
            <%= link_to 'Odtwarzaj', song_url(s.song_id), :remote => true %>
            <%= link_to 'Kolejkuj', add_to_playlist_url(s.song_id), :remote => true %>
          </td>

        </tr>
      <% end %>
    </table>
<% else %>
    dupa.
<% end %>

app/views/songs/show.js.erb
//console.log(($('#player').find('audio'));
$('#player').find('audio').find('source').attr('src', '<%= song_url(@song, :format => :mp3) %>');
$('#player').find('audio')[0].load();
$('#player').find('audio')[0].play();